type: file
functions:
  - name: file_read
    description: Read contents of a file
    parameters:
      type: object
      properties:
        path:
          type: string
          description: Path to the file to read
        encoding:
          type: string
          description: File encoding
          default: utf-8
      required: [path]
      examples:
        - {file_read: {path: "/path/to/file.txt"}}
        - {file_read: {path: "data.json", encoding: "utf-8"}}

  - name: file_write
    description: Write content to a file
    parameters:
      type: object
      properties:
        path:
          type: string
          description: Path to write the file to
        content:
          type: string
          description: Content to write to the file
        encoding:
          type: string
          description: File encoding
          default: utf-8
      required: [path, content]
      examples:
        - {file_write: {path: "output.txt", content: "Hello, World!"}}
        - {file_write: {path: "data.json", content: "{\"key\": \"value\"}", encoding: "utf-8"}}

  - name: file_list
    description: List contents of a directory
    parameters:
      type: object
      properties:
        path:
          type: string
          description: Directory path to list
        pattern:
          type: string
          description: Optional glob pattern to filter files
      required: [path]
      examples:
        - {file_list: {path: "/path/to/dir"}}
        - {file_list: {path: ".", pattern: "*.py"}}

  - name: file_delete
    description: Delete a file
    parameters:
      type: object
      properties:
        path:
          type: string
          description: Path of the file to delete
      required: [path]
      examples:
        - {file_delete: {path: "temp.txt"}}

  - name: file_move
    description: Move or rename a file
    parameters:
      type: object
      properties:
        source:
          type: string
          description: Source file path
        destination:
          type: string
          description: Destination file path
      required: [source, destination]
      examples:
        - {file_move: {source: "old.txt", destination: "new.txt"}}
        - {file_move: {source: "file.txt", destination: "backup/file.txt"}}

implementation:
  module: aim.tool.impl.file_ops
  class: FileOperationsImplementation 