type: knowledge_base
functions:
  - name: query_knowledge_base
    description: Query the knowledge base for information
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The query to search in the knowledge base
        max_results:
          type: integer
          description: Maximum number of results to return
          default: 5
      required: [query]
      examples:
        - {query_knowledge_base: {query: "What is the capital of France?"}}
        - {query_knowledge_base: {query: "How does photosynthesis work?", max_results: 3}}
implementation:
  module: aim.tool.impl.passback
  class: PassBackImplementation 