type: media
functions:
  - name: play_music
    description: Play music from a specified source
    parameters:
      type: object
      properties:
        source:
          type: string
          description: The source of the music (URL, file path, or search query)
        volume:
          type: integer
          description: Playback volume (0-100)
          minimum: 0
          maximum: 100
          default: 50
        repeat:
          type: boolean
          description: Whether to repeat the playback
          default: false
      required: [source]
      examples:
        - {play_music: {source: "https://example.com/song.mp3", volume: 75}}
        - {play_music: {source: "Mozart Symphony No. 40", repeat: true}}
implementation:
  module: aim.tool.impl.passback
  class: PassBackImplementation 