type: memory
functions:
  - name: pin_memory
    description: Pin a piece of information to memory
    parameters:
      type: object
      properties:
        conversation_id:
          type: string
          description: The conversation id
      required: [conversation_id]
      examples:
        - {pin_memory: {conversation_id: "conv_memory_12345"}}

  - name: unpin
    description: Remove a piece of information from pinned memory
    parameters:
      type: object
      properties:
        key:
          type: string
          description: The key of the memory to unpin
      required: [key]
      examples:
        - {unpin_memory: {key: "user_temp_pref"}}