type: pipeline
functions:
  - name: list_pipelines
    description: List available pipelines
    parameters:
      type: object
      properties:
        status:
          type: string
          description: Filter by pipeline status (all, running, completed)
          enum: [all, running, completed]
          default: all
      examples:
        - {list_pipelines: {status: "running"}}
        - {list_pipelines: {status: "all"}}

  - name: run_pipeline
    description: Run a pipeline
    parameters:
      type: object
      properties:
        pipeline_id:
          type: string
          description: ID of the pipeline to run
        parameters:
          type: object
          description: Pipeline-specific parameters
      required: [pipeline_id]
      examples:
        - {run_pipeline: {pipeline_id: "data_processing_001"}}
        - {run_pipeline: {pipeline_id: "ml_training_002", parameters: {epochs: 100, batch_size: 32}}}

  - name: get_pipeline_status
    description: Get detailed status of a specific pipeline
    parameters:
      type: object
      properties:
        pipeline_id:
          type: string
          description: ID of the pipeline to check
      required: [pipeline_id]
      examples:
        - {get_pipeline_status: {pipeline_id: "data_processing_001"}}

  - name: cancel_pipeline
    description: Cancel a running pipeline
    parameters:
      type: object
      properties:
        pipeline_id:
          type: string
          description: ID of the pipeline to cancel
      required: [pipeline_id]
      examples:
        - {cancel_pipeline: {pipeline_id: "data_processing_001"}}

implementation:
  module: aim.tool.impl.pipeline
  class: PipelineImplementation 