type: system
functions:
  - name: system_run_command
    description: Run a bash command
    parameters:
      type: object
      properties:
        command:
          type: string
          description: The command to run
        working_dir:
          type: string
          description: Working directory for command execution
          default: .
      required: [command]
      examples:
        - {system_run_command: {command: "ls -la"}}
        - {system_run_command: {command: "ps aux", working_dir: "/tmp"}}

  - name: system_run_python
    description: Execute a Python script
    parameters:
      type: object
      properties:
        code:
          type: string
          description: Python code to execute
        working_dir:
          type: string
          description: Working directory for execution
          default: .
      required: [code]
      examples:
        - {system_run_python: {code: "print('Hello, world!')"}}
        - {system_run_python: {code: "import os\nprint(os.listdir('.'))"}}

  - name: system_env_var
    description: Get environment variable values
    parameters:
      type: object
      properties:
        var_name:
          type: string
          description: Specific environment variable to get (optional)
      examples:
        - {system_env_var: {var_name: "PATH"}}
        - {system_env_var: {}}

implementation:
  module: aim.tool.impl.system
  class: SystemImplementation 