type: system
functions:
  - name: system_process_info
    description: Get information about running processes
    parameters:
      type: object
      properties:
        pid:
          type: integer
          description: Process ID to get info for (optional, if not provided returns all processes)
        format:
          type: string
          description: Output format
          enum: [short, full]
          default: short
      examples:
        - {system_process_info: {pid: 1234}}
        - {system_process_info: {format: full}}

  - name: system_env_var
    description: Get environment variable value
    parameters:
      type: object
      properties: {}
      required: []
      examples:
        - {system_env_var: {}}

  - name: system_run_command
    description: Run a bash command
    parameters:
      type: object
      properties:
        command:
          type: string
          description: The command to run
        working_dir:
          type: string
          description: Working directory for command execution
          default: .
      required: [command]
      examples:
        - {system_run_command: {command: "ls -la"}}
        - {system_run_command: {command: "ps aux", working_dir: "/tmp"}}
implementation:
  module: aim.tool.impl.system
  class: SystemImplementation 