type: web
functions:
  - name: search_web
    description: Use a search engine to find information on the web
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The query to search the web for
      required: [query]
      examples:
        - {search_web: {query: "latest developments in quantum computing"}}
        - {search_web: {query: "who won the presidential election in the United States"}}
implementation:
  module: aim.tool.impl.passback
  class: PassBackImplementation 