type: web
functions:
  - name: scrape_web_url
    description: Scrape a URL and return the content
    parameters:
      type: object
      properties:
        url:
          type: string
          description: The URL to open in the browser
      required: [url]
      examples:
        - {scrape_web_url: {url: "https://www.google.com"}}
        - {scrape_web_url: {url: "https://github.com"}}
implementation:
  module: aim.tool.impl.passback
  class: PassBackImplementation 