type: wikipedia
functions:
  - name: search_wikipedia
    description: Search Wikipedia for information
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The query to search Wikipedia for
      required: [query]
      examples:
        - {search_wikipedia: {query: "United States Constitution"}}
        - {search_wikipedia: {query: "Remote procedure call"}}
implementation:
  module: aim.tool.impl.passback
  class: PassBackImplementation 