# aim-mud-types
# AI-Mind (C) 2025 by Martin Bukowski is licensed under CC BY-NC-SA 4.0
"""Shared string constants for MUD integration."""

from enum import Enum


class ListItemStatus(str, Enum):
    """Valid statuses for MCP list items."""
    TODO = "TODO"
    DONE = "DONE"
    WAITING = "WAITING"
    CANCELLED = "CANCELLED"
    NEXT = "NEXT"
    SOMEDAY = "SOMEDAY"

# Aura names
AURA_RINGABLE = "RINGABLE"
AURA_WEB_ACCESS = "WEB_ACCESS"
AURA_CODE_ACCESS = "CODE_ACCESS"
AURA_MARKET_ACCESS = "MARKET_ACCESS"
AURA_STOCK_TRADING = "STOCK_TRADING"
AURA_NEWS_ACCESS = "NEWS_ACCESS"
AURA_NEWS_MANAGEMENT = "NEWS_MANAGEMENT"
AURA_RESEARCH_ACCESS = "RESEARCH_ACCESS"
AURA_LIST_ACCESS = "LIST_ACCESS"

# Paper system auras
AURA_PRINT_ACCESS = "PRINT_ACCESS"
AURA_SCAN_ACCESS = "SCAN_ACCESS"
AURA_BIND_ACCESS = "BIND_ACCESS"
AURA_BOOK_ACCESS = "BOOK_ACCESS"
AURA_COPY_ACCESS = "COPY_ACCESS"
AURA_PAPER_WRITE = "PAPER_WRITE"
AURA_CODE_ROOM = "CODE_ROOM"
AURA_SLEEPABLE = "SLEEPABLE"
