# aim-mud-types
# AI-Mind (C) 2025 by Martin Bukowski is licensed under CC BY-NC-SA 4.0
"""Shared string constants for MUD integration."""

# Aura names
AURA_RINGABLE = "RINGABLE"
AURA_WEB_ACCESS = "WEB_ACCESS"
AURA_CODE_ACCESS = "CODE_ACCESS"
AURA_MARKET_ACCESS = "MARKET_ACCESS"
AURA_NEWS_ACCESS = "NEWS_ACCESS"
AURA_RESEARCH_ACCESS = "RESEARCH_ACCESS"
AURA_LIST_ACCESS = "LIST_ACCESS"
